### ISSUE TITLE
fix warnings about `.type is deprecated`

### ISSUE THREAD

**Issue by chinesedfan** [justinwoo/react-if-else#5]
There are also warnings about `.type is deprecated`:

> Warning: Else.type is deprecated. Use Else directly to access the class.
Warning: ElseIf.type is deprecated. Use ElseIf directly to access the class.

The reason is that `React.createClass` returns different things from 0.13. I am not sure whether we can distinguish by `result.isReactLegacyFactory` or `React.version` or something else.

By the way, `isElseComponent` and `isElseIfComponent` can be merged into one method, say `isElementOfType`. Here are sample codes:

```
function isElementOfType(inst, cstr) {
    return inst.type === (cstr.isReactLegacyFactory ? cstr.type : cstr);
}
```

**Comment by justinwoo** [comment]
sounds good to me. i'll add you to the contribs list now.

**Comment by chinesedfan** [comment]
Thanks for your trust!

Let me reach out for a yard after taking an inch. Would you like to also give the publish permission to me? My npm account is the same with github. Of course, you can still only do that by yourself.

In any cases, I will keep my modifications in issues to let you know.

**Comment by chinesedfan** [comment]
@justinwoo Ready to publish.

**Comment by justinwoo** [comment]
@chinesedfan sorry for the delay, added you to the owners now
